apiVersion: v1
kind: Service
metadata:
  name: unit3d-app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: unit3d-app
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
      appProtocol: http
