apiVersion: apps/v1
kind: Deployment
metadata:
  name: unit3d-app
spec:
  template:
    spec:
      containers:
        - name: unit3d-app
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
