{{- if and .Values.redis.enabled (not .Values.redis.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ratatoskr.redis.fullname" . }}
  labels:
    {{- include "ratatoskr.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
    app.kubernetes.io/name: redis
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.redis.auth.password | quote }}
{{- end }}
