{{- if and .Values.meilisearch.enabled (not .Values.meilisearch.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ratatoskr.meilisearch.fullname" . }}
  labels:
    {{- include "ratatoskr.labels" . | nindent 4 }}
    app.kubernetes.io/component: search
    app.kubernetes.io/name: meilisearch
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  MEILI_MASTER_KEY: {{ .Values.meilisearch.masterKey | quote }}
{{- end }}
